name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auto-Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          approve: true
          github-token: ${{ secrets.GH_TOKEN }}

